apiVersion: v1
data:
  config: |2
    [global]
    user=10000
    group=10000
    # Output directory path is expected to exist
    output_dir=/home/10000/whisper/secrets
    cache_file=/home/10000/whisper/secrets/whisper.cache
    [app]
    # Certificate, key, and directory relative to this app
    certificate=/home/10000/tls/tls.crt
    private_key=/home/10000/tls/tls.key
    directory=/home/10000/whisper/secrets/app
kind: ConfigMap
metadata:
  name: whisper-client-configmap
  namespace: default